Update to support multiple architectures!
https://github.com/docker/build-push-action#multi-platform-image

Upgrade from docker/build-push-action v1 to v2: https://github.com/docker/build-push-action/blob/master/UPGRADE.md#tags-with-ref-and-git-labels

Build base image changed from edge to 3.12 because of openssl error.
```
#90 [linux/arm64 build 6/6] RUN autoreconf -fiv     && CC="clang" CFLAGS="-O...
#90 CANCELED
------
 > [linux/amd64 build 6/6] RUN autoreconf -fiv     && CC="clang" CFLAGS="-O3 -static" LIBS="$(pkg-config --libs openssl)" ./configure --prefix="" --enable-utf8 --with-openssl --enable-geoip=mmdb     && make     && make DESTDIR=/dist install:
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c autoreconf -fiv     && CC="clang" CFLAGS="-O3 -static" LIBS="$(pkg-config --libs openssl)" ./configure --prefix="" --enable-utf8 --with-openssl --enable-geoip=mmdb     && make     && make DESTDIR=/dist install]: exit code: 1
Error: buildx call failed with: failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c autoreconf -fiv     && CC="clang" CFLAGS="-O3 -static" LIBS="$(pkg-config --libs openssl)" ./configure --prefix="" --enable-utf8 --with-openssl --enable-geoip=mmdb     && make     && make DESTDIR=/dist install]: exit code: 1
```

Main base image changed to https://github.com/crazy-max/docker-alpine-s6 in order to easily support multiple base architectures.

Closes #11